import { expect, test } from "bun:test";
import { normalize, renderVars } from "./normalize";
import type { ResolvedSpec } from "./types";

const resolved: ResolvedSpec = {
  config_version: 3,
  platform: { distribution: "ubuntu", version: "26.04", architecture: "amd64" },
  operator: { user: "devbox-admin", ssh_authorized_keys: ["ssh-ed25519 AAAA k@c"] },
  network: { tailscale: { enabled: true }, ssh: { access: ["public", "tailnet"] } },
  container: { default_engine: "podman-rootless", install_engines: ["podman-rootless"] },
  developers: [
    {
      user: "dev-a",
      login_ssh_keys: ["ssh-ed25519 AAAA k@c"],
      git_identities: { work: { name: "N", email: "e@example.com" } },
      projects: [
        {
          name: "p",
          repo: "git@github.com:example/p.git",
          branch: "main",
          git_identity: "work",
          agent_profile: null,
          container_engine: "podman-rootless",
          memory_space: null,
          ports: [],
          install: true,
          update: false,
        },
      ],
    },
  ],
};

const dev0 = () => (normalize(resolved).devbox_developers as Record<string, unknown>[])[0]!;

test("absent optionals become concrete values, never undefined", () => {
  const dev = dev0();
  expect(dev.adopt_existing).toBe(false);
  expect(dev.resources).toEqual({});
  expect(dev.agent_profiles).toEqual({});
  expect(dev.default_agent_profile).toBeNull();
  expect(dev.container_engine).toBeNull();
  expect(dev.memory).toEqual({ enabled: false, default_space: null, instances: {}, spaces: {} });
  expect(dev.desktop).toEqual({
    enabled: false,
    environment: "xfce",
    transport: "xrdp",
    access: ["tunnel", "tailnet"],
    idle_logout_minutes: null,
    keyboard: null,
  });
});

test("a git identity is emitted with an explicit github_user", () => {
  expect(dev0().git_identities).toEqual({ work: { name: "N", email: "e@example.com", github_user: null } });
});

test("shared_services defaults to disabled", () => {
  expect(normalize(resolved).devbox_shared_services).toEqual({ enabled: false, engine: "system-docker" });
});

test("declared resources survive normalization", () => {
  const withLimits: ResolvedSpec = {
    ...resolved,
    developers: [{ ...resolved.developers[0]!, resources: { memory_high: "10G", cpu_weight: 100 } }],
  };
  const dev = (normalize(withLimits).devbox_developers as Record<string, unknown>[])[0]!;
  expect(dev.resources).toEqual({ memory_high: "10G", cpu_weight: 100 });
});

test("file_bridge defaults to off with the mutagen engine", () => {
  const dev = dev0();
  expect(dev.file_bridge).toEqual({ sync_disk: false, engine: "mutagen" });
});

test("a declared file_bridge survives normalization", () => {
  const withBridge: ResolvedSpec = {
    ...resolved,
    developers: [{ ...resolved.developers[0]!, file_bridge: { sync_disk: true, engine: "syncthing" } }],
  };
  const dev = (normalize(withBridge).devbox_developers as Record<string, unknown>[])[0]!;
  expect(dev.file_bridge).toEqual({ sync_disk: true, engine: "syncthing" });
});

test("renderVars emits a do-not-edit header and parses back", () => {
  const text = renderVars(resolved);
  expect(text.startsWith("---\n# GENERATED by `devbox plan`")).toBe(true);
  const parsed = Bun.YAML.parse(text) as Record<string, unknown>;
  expect(parsed.devbox_config_version).toBe(3);
  expect((parsed.devbox_developers as Record<string, unknown>[])[0]!.user).toBe("dev-a");
});

test("normalization is deterministic", () => {
  expect(renderVars(resolved)).toBe(renderVars(structuredClone(resolved)));
});

const withDesktop = (desktop: Record<string, unknown>): ResolvedSpec => ({
  ...resolved,
  developers: [{ ...resolved.developers[0]!, desktop: { enabled: true, environment: "xfce", transport: "xrdp", ...desktop } as any }],
});

const desktopOf = (out: Record<string, unknown>): any => (out.devbox_developers as any[])[0].desktop;

test("an unstated keyboard falls back to the one the client types on", () => {
  const out = normalize(withDesktop({}), { keyboard: { layout: "tr", variant: null } });
  expect(desktopOf(out).keyboard).toEqual({ layout: "tr", variant: null, rdp_layout_id: "0x0000041F" });
});

test("a stated keyboard beats the detected one", () => {
  const out = normalize(withDesktop({ keyboard: { layout: "de" } }), {
    keyboard: { layout: "tr", variant: null },
  });
  expect(desktopOf(out).keyboard).toEqual({ layout: "de", variant: null, rdp_layout_id: "0x00000407" });
});

test("a stated keyboard keeps its variant", () => {
  const out = normalize(withDesktop({ keyboard: { layout: "tr", variant: "f" } }), { keyboard: null });
  expect(desktopOf(out).keyboard).toEqual({ layout: "tr", variant: "f", rdp_layout_id: "0x0001041F" });
});

// Undetected and unstated leaves the layout to the box rather than guessing at one.
test("no keyboard anywhere stays null", () => {
  expect(desktopOf(normalize(withDesktop({}))).keyboard).toBeNull();
});

test("a box without Tailscale defaults to the paths that actually exist", () => {
  const noTailnet: ResolvedSpec = {
    ...resolved,
    network: { tailscale: { enabled: false }, ssh: {} },
    developers: [{ ...resolved.developers[0]!, desktop: { enabled: true, environment: "xfce", transport: "xrdp" } }],
  };
  const out = normalize(noTailnet);
  expect((out.devbox_network as any).ssh.access).toEqual(["public"]);
  expect(((out.devbox_developers as any[])[0]).desktop.access).toEqual(["tunnel"]);
});

test("swappiness is null when unset, so the role leaves the kernel default alone", () => {
  expect((normalize(resolved).devbox_host as any).swappiness).toBeNull();
  const tuned: ResolvedSpec = { ...resolved, host: { swappiness: 10 } };
  expect((normalize(tuned).devbox_host as any).swappiness).toBe(10);
});
