/**
 * normalize.ts — turn a resolved spec into the `devbox_*` variables Ansible consumes.
 *
 * Two rules drive everything here:
 *  1. Every key is prefixed `devbox_`, so generated vars can never collide with Ansible
 *     facts or with a leftover `group_vars/all.yml`.
 *  2. Nothing is optional in the output. An absent optional becomes `null`, `false`,
 *     `{}` or `[]` — so no role ever needs a Jinja `| default(...)`, and a missing key
 *     in a template is a real bug rather than a silent policy decision.
 */
import type {
  GitIdentity,
  MemoryInstance,
  MemorySpace,
  ResolvedDeveloper,
  ResolvedSpec,
} from "./types";
import { toYaml } from "./yaml";

const GENERATED_HEADER = [
  "---",
  "# GENERATED by `devbox plan` — DO NOT EDIT.",
  "# Source of truth: devbox.yml (+ devbox.secrets.yml). Re-run `devbox plan` to refresh.",
  "",
].join("\n");

export function normalize(resolved: ResolvedSpec): Record<string, unknown> {
  return {
    devbox_config_version: resolved.config_version,
    devbox_platform: {
      distribution: resolved.platform.distribution,
      version: resolved.platform.version,
      architecture: resolved.platform.architecture,
    },
    devbox_runtimes: { ...(resolved.runtimes ?? {}) },
    devbox_host: {
      swap_size: resolved.host?.swap_size ?? "4G",
      zram: {
        enabled: resolved.host?.zram?.enabled ?? false,
        percent: resolved.host?.zram?.percent ?? 50,
        algo: resolved.host?.zram?.algo ?? "zstd",
        // Above the disk swapfile's -1 so compressed RAM is used first.
        priority: resolved.host?.zram?.priority ?? 100,
      },
      locales: [...(resolved.host?.locales ?? ["en_US.UTF-8"])],
      mosh: resolved.host?.mosh ?? true,
      eternal_terminal: resolved.host?.eternal_terminal ?? false,
      harden_ssh: resolved.host?.harden_ssh ?? true,
      hide_pids: resolved.host?.hide_pids ?? true,
      umask: resolved.host?.umask ?? "077",
    },
    devbox_operator: {
      user: resolved.operator.user,
      ssh_authorized_keys: [...resolved.operator.ssh_authorized_keys],
      private_key_path: resolved.operator.private_key_path ?? "~/.ssh/id_ed25519",
    },
    devbox_network: {
      tailscale: { enabled: resolved.network.tailscale.enabled },
      ssh: { exposure: resolved.network.ssh.exposure },
    },
    devbox_container: {
      default_engine: resolved.container.default_engine,
      install_engines: [...resolved.container.install_engines],
    },
    devbox_shared_services: {
      enabled: resolved.shared_services?.enabled ?? false,
      engine: resolved.shared_services?.engine ?? "system-docker",
    },
    devbox_developers: resolved.developers.map(normalizeDeveloper),
  };
}

function normalizeDeveloper(dev: ResolvedDeveloper): Record<string, unknown> {
  return {
    user: dev.user,
    adopt_existing: dev.adopt_existing ?? false,
    login_ssh_keys: [...dev.login_ssh_keys],
    resources: {
      ...(dev.resources?.memory_high !== undefined ? { memory_high: dev.resources.memory_high } : {}),
      ...(dev.resources?.memory_max !== undefined ? { memory_max: dev.resources.memory_max } : {}),
      ...(dev.resources?.memory_swap_max !== undefined ? { memory_swap_max: dev.resources.memory_swap_max } : {}),
      ...(dev.resources?.cpu_weight !== undefined ? { cpu_weight: dev.resources.cpu_weight } : {}),
      ...(dev.resources?.io_weight !== undefined ? { io_weight: dev.resources.io_weight } : {}),
      ...(dev.resources?.tasks_max !== undefined ? { tasks_max: dev.resources.tasks_max } : {}),
    },
    container_engine: dev.container_engine ?? null,
    git_identities: mapValues(dev.git_identities, normalizeIdentity),
    default_git_identity: dev.default_git_identity ?? null,
    agent_profiles: mapValues(dev.agent_profiles, (p) => ({
      provider: p.provider,
      memory_space: p.memory_space ?? null,
    })),
    default_agent_profile: dev.default_agent_profile ?? null,
    memory: {
      enabled: dev.memory?.enabled ?? false,
      default_space: dev.memory?.default_space ?? null,
      instances: mapValues(dev.memory?.instances, normalizeInstance),
      spaces: mapValues(dev.memory?.spaces, (s: MemorySpace) => ({ instance: s.instance, bank: s.bank })),
    },
    desktop: {
      enabled: dev.desktop?.enabled ?? false,
      environment: dev.desktop?.environment ?? "xfce",
      transport: dev.desktop?.transport ?? "xrdp",
      // Tunnel-only by default: the RDP prompt is then unreachable without an SSH key,
      // which turns the PAM password from the exposed gate into a second factor.
      access: [...(dev.desktop?.access ?? ["tunnel"])],
      idle_logout_minutes: dev.desktop?.idle_logout_minutes ?? null,
    },
    projects: dev.projects.map((p) => ({
      name: p.name,
      repo: p.repo,
      branch: p.branch,
      git_identity: p.git_identity,
      agent_profile: p.agent_profile,
      container_engine: p.container_engine,
      memory_space: p.memory_space,
      ports: [...p.ports],
      install: p.install,
      update: p.update,
    })),
  };
}

const normalizeIdentity = (id: GitIdentity) => ({
  name: id.name,
  email: id.email,
  github_user: id.github_user ?? null,
});

const normalizeInstance = (i: MemoryInstance) => ({
  engine: i.engine,
  llm_provider: i.llm_provider,
  llm_model: i.llm_model ?? null,
  llm_base_url: i.llm_base_url ?? null,
  api_key_env: i.api_key_env ?? null,
});

function mapValues<T, R>(
  source: Record<string, T> | undefined,
  fn: (value: T) => R,
): Record<string, R> {
  const out: Record<string, R> = {};
  for (const [key, value] of Object.entries(source ?? {})) out[key] = fn(value);
  return out;
}

/** The full generated vars file, header included. */
export function renderVars(resolved: ResolvedSpec): string {
  return GENERATED_HEADER + toYaml(normalize(resolved));
}
