/**
 * normalize.ts — turn a resolved spec into the `devbox_*` variables Ansible consumes.
 *
 * Two rules drive everything here:
 *  1. Every key is prefixed `devbox_`, so generated vars can never collide with Ansible
 *     facts or with a leftover `group_vars/all.yml`.
 *  2. Nothing is optional in the output. An absent optional becomes `null`, `false`,
 *     `{}` or `[]` — so no role ever needs a Jinja `| default(...)`, and a missing key
 *     in a template is a real bug rather than a silent policy decision.
 */
import { assignClientPorts } from "./client-ports";
import {
  assignMcpPorts,
  browserUsers,
  DEFAULT_CDP_PORT,
  DEFAULT_CLIENT_TUNNEL_PORT,
  DEFAULT_FALLBACK_CHROME_PORT,
  DEFAULT_MCP_PORT,
} from "./browser-ports";
import { DEFAULT_CLI_TARGETS, SERVICE_RESOURCE_KEYS, SLICE_RESOURCE_KEYS } from "./types";
import type {
  ClientFacts,
  GitIdentity,
  MemoryInstance,
  MemorySpace,
  ResolvedDeveloper,
  ResolvedKeyboard,
  ResolvedSpec,
  ResourceSpec,
} from "./types";
import { defaultDesktopAccess, defaultSshAccess } from "./resolve";
import { rdpLayoutId } from "./rdp-layouts";
import { toYaml } from "./yaml";
import { payloadBasename, resolveEntry } from "../app-configs/registry";
import { canonicalMemorySize, isMemoryWeight } from "./memory-limit";

const GENERATED_HEADER = [
  "---",
  "# GENERATED by `devbox plan` — DO NOT EDIT.",
  "# Source of truth: devbox.yml (+ devbox.secrets.yml). Re-run `devbox plan` to refresh.",
  "",
].join("\n");

/** No client facts is the honest default: detection is best-effort and may find nothing. */
const NO_CLIENT_FACTS: ClientFacts = { keyboard: null };

export function normalize(resolved: ResolvedSpec, client: ClientFacts = NO_CLIENT_FACTS): Record<string, unknown> {
  const tailscale = resolved.network.tailscale.enabled;
  const memoryHighWeightTotal = resolved.developers.reduce((total, developer) => {
    const memoryHigh = developer.resources?.memory_high;
    return total + (isMemoryWeight(memoryHigh) ? memoryHigh.weight : 0);
  }, 0);
  const mcpBasePort = resolved.browser?.mcp_port ?? DEFAULT_MCP_PORT;
  const clientPorts = assignClientPorts(
    resolved.developers.map((d) => ({
      user: d.user,
      desktopEnabled: d.desktop?.enabled ?? false,
      clientPort: d.desktop?.client_port,
    })),
  );
  return {
    devbox_config_version: resolved.config_version,
    devbox_platform: {
      distribution: resolved.platform.distribution,
      version: resolved.platform.version,
      architecture: resolved.platform.architecture,
    },
    devbox_runtimes: { ...(resolved.runtimes ?? {}) },
    devbox_host: {
      swap_size: resolved.host?.swap_size ?? "4G",
      memory_reserve: canonicalMemorySize(resolved.host?.memory_reserve ?? "4G")!,
      zram: {
        enabled: resolved.host?.zram?.enabled ?? false,
        percent: resolved.host?.zram?.percent ?? 50,
        algo: resolved.host?.zram?.algo ?? "zstd",
        // Above the disk swapfile's -1 so compressed RAM is used first.
        priority: resolved.host?.zram?.priority ?? 100,
      },
      locales: [...(resolved.host?.locales ?? ["en_US.UTF-8"])],
      mosh: resolved.host?.mosh ?? true,
      eternal_terminal: resolved.host?.eternal_terminal ?? false,
      harden_ssh: resolved.host?.harden_ssh ?? true,
      hide_pids: resolved.host?.hide_pids ?? true,
      github_cli: resolved.host?.github_cli ?? true,
      umask: resolved.host?.umask ?? "077",
      swappiness: resolved.host?.swappiness ?? null,
      oomd: {
        enabled: resolved.host?.oomd?.enabled ?? true,
        memory_pressure_limit: resolved.host?.oomd?.memory_pressure_limit ?? "60%",
        memory_pressure_duration_sec: resolved.host?.oomd?.memory_pressure_duration_sec ?? 20,
      },
    },
    devbox_operator: {
      user: resolved.operator.user,
      ssh_authorized_keys: [...resolved.operator.ssh_authorized_keys],
      private_key_path: resolved.operator.private_key_path ?? "~/.ssh/id_ed25519",
    },
    devbox_network: {
      tailscale: { enabled: resolved.network.tailscale.enabled },
      ssh: { access: resolved.network.ssh.access ?? defaultSshAccess(resolved.network.tailscale.enabled) },
    },
    devbox_container: {
      default_engine: resolved.container.default_engine,
      install_engines: [...resolved.container.install_engines],
    },
    devbox_shared_services: {
      enabled: resolved.shared_services?.enabled ?? false,
      engine: resolved.shared_services?.engine ?? "system-docker",
    },
    devbox_clients: {
      // The three platforms a developer laptop is usually one of. linux-arm64 is left
      // out of the default because each target costs a ~60-90MB build and upload, and an
      // operator who has such a laptop on the team is the one who knows it.
      cli_targets: [...(resolved.clients?.cli_targets ?? DEFAULT_CLI_TARGETS)],
    },
    // One generated value feeds both the memory role and the sanitized health facts.
    // Keeping two role-local defaults would let the daemon and doctor disagree.
    devbox_memory_base_port: 9077,
    devbox_memory_high_weight_total: memoryHighWeightTotal,
    devbox_browser: {
      enabled: resolved.browser?.enabled ?? true,
      mcp_port: mcpBasePort,
      // One row per browser-enabled developer, each naming the account its server runs
      // as and the port that server owns. The role loops this directly: the unit's
      // `User=` and the URL each developer is wired with both come from the same row,
      // so a session can never be pointed at a server running as someone else.
      servers: assignMcpPorts(browserUsers(resolved.developers), mcpBasePort),
      failover: {
        enabled: resolved.browser?.failover?.enabled ?? false,
        // Named, never inferred: this account's Chrome is the one the endpoint serves.
        // It says who runs the fallback browser and nothing else — the MCP servers run
        // as their own developer, whether or not failover is on.
        chrome_user: resolved.browser?.failover?.chrome_user ?? null,
        cdp_port: resolved.browser?.failover?.cdp_port ?? DEFAULT_CDP_PORT,
        fallback_chrome_port: resolved.browser?.failover?.fallback_chrome_port ?? DEFAULT_FALLBACK_CHROME_PORT,
        client_tunnel_port: resolved.browser?.failover?.client_tunnel_port ?? DEFAULT_CLIENT_TUNNEL_PORT,
        autobind: resolved.browser?.failover?.autobind ?? false,
      },
    },
    devbox_remote_control: normalizeRemoteControl(resolved),
    devbox_rc_units: normalizeRcUnits(resolved),
    devbox_codex_units: normalizeCodexUnits(resolved),
    devbox_developers: resolved.developers.map((dev) => normalizeDeveloper(dev, tailscale, client, clientPorts)),
  };
}

/**
 * The box-wide Remote Control block, fully defaulted. `skip_workflow_warning` follows
 * `on_boot` because a resumed session that stops for a usage prompt has not been
 * resumed — pinning it separately is the exception, not the rule.
 */
function normalizeRemoteControl(resolved: ResolvedSpec): Record<string, unknown> {
  const rc = resolved.remote_control ?? {};
  const ar = rc.autorestart ?? {};
  const re = rc.resume ?? {};
  const onBoot = re.on_boot ?? true;
  return {
    enabled: rc.enabled ?? true,
    autorestart: {
      enabled: ar.enabled ?? true,
      restart_sec: ar.restart_sec ?? 10,
      burst: ar.burst ?? 10,
      interval: ar.interval ?? 600,
    },
    resume: {
      on_boot: onBoot,
      lookback_h: re.lookback_h ?? 12,
      max_concurrent: re.max_concurrent ?? 2,
      settle_sec: re.settle_sec ?? 20,
      min_free_mb: re.min_free_mb ?? 1200,
      max_attempts: re.max_attempts ?? 3,
      timeout_sec: re.timeout_sec ?? 1800,
      skip_workflow_warning: re.skip_workflow_warning ?? onBoot,
    },
  };
}

/** (developer × project) flattened to one row per unit — the role loops this directly. */
function normalizeRcUnits(resolved: ResolvedSpec): Record<string, unknown>[] {
  return resolved.developers.flatMap((dev) =>
    dev.projects.flatMap((p) => {
      const rc = p.remote_control;
      if (!rc) return [];
      return [
        {
          user: dev.user,
          project: p.name,
          agent: rc.agent,
          agent_profile: rc.agent_profile,
          name: rc.name,
          spawn: rc.spawn,
          capacity: rc.capacity,
          project_dir: `/home/${dev.user}/projects/${p.name}`,
          resources: normalizeDirectMemoryResources(rc.resources, true),
          build_env: { ...rc.build_env },
        },
      ];
    }),
  );
}

/**
 * Codex's remote control is a per-PROFILE daemon, not a per-project session host: its
 * CLI takes no name/spawn/capacity, and one daemon serves every project that profile
 * opens. So codex units are keyed by agent profile while Claude's stay keyed by
 * project — the same containment policy, a different unit shape.
 *
 * They exist for the reason Remote Control units do: everything a session spawns lands
 * in this cgroup, so it is where a runaway build is contained and what has to carry
 * `ManagedOOMPreference=avoid`. A codex daemon started outside Ansible does not: one
 * run by hand on 2026-08-12 sat at the oomd default and was killed with all 25
 * processes in it eighteen times, taking every live session down each time.
 *
 * Limits come from the box-wide `remote_control.resources` because a codex daemon
 * competes for the same host as the Claude units and should be bounded like them; a
 * profile has no resources block of its own to read.
 */
function normalizeCodexUnits(resolved: ResolvedSpec): Record<string, unknown>[] {
  const resources = normalizeDirectMemoryResources(resolved.remote_control?.resources ?? {}, true);
  return resolved.developers.flatMap((dev) =>
    Object.entries(dev.agent_profiles ?? {})
      .filter(([, profile]) => profile.provider === "codex")
      .map(([profile]) => ({
        user: dev.user,
        profile,
        codex_home: `/home/${dev.user}/.agent-profiles/${profile}`,
        resources,
      })),
  );
}

function normalizeDeveloper(
  dev: ResolvedDeveloper,
  tailscale: boolean,
  client: ClientFacts,
  clientPorts: Map<string, number>,
): Record<string, unknown> {
  const memoryHigh = dev.resources?.memory_high;
  const { memory_high: _memoryHigh, ...directResources } = normalizeDirectMemoryResources(dev.resources ?? {});
  return {
    user: dev.user,
    adopt_existing: dev.adopt_existing ?? false,
    login_ssh_keys: [...dev.login_ssh_keys],
    resources: {
      ...directResources,
      ...(typeof memoryHigh === "string"
        ? { memory_high: canonicalMemorySize(memoryHigh) ?? memoryHigh }
        : isMemoryWeight(memoryHigh)
          ? { memory_high_weight: memoryHigh.weight }
          : {}),
    },
    container_engine: dev.container_engine ?? null,
    git_identities: mapValues(dev.git_identities, normalizeIdentity),
    default_git_identity: dev.default_git_identity ?? null,
    agent_profiles: mapValues(dev.agent_profiles, (p) => ({
      provider: p.provider,
      memory_space: p.memory_space ?? null,
    })),
    default_agent_profile: dev.default_agent_profile ?? null,
    memory: {
      enabled: dev.memory?.enabled ?? false,
      default_space: dev.memory?.default_space ?? null,
      instances: mapValues(dev.memory?.instances, normalizeInstance),
      spaces: mapValues(dev.memory?.spaces, (s: MemorySpace) => ({ instance: s.instance, bank: s.bank })),
    },
    desktop: {
      enabled: dev.desktop?.enabled ?? false,
      environment: dev.desktop?.environment ?? "xfce",
      transport: dev.desktop?.transport ?? "xrdp",
      // Tunnel-only by default: the RDP prompt is then unreachable without an SSH key,
      // which turns the PAM password from the exposed gate into a second factor.
      access: [...(dev.desktop?.access ?? defaultDesktopAccess(tailscale))],
      idle_logout_minutes: dev.desktop?.idle_logout_minutes ?? null,
      client_port: clientPorts.get(dev.user) ?? null,
      keyboard: resolveKeyboard(dev, client),
    },
    file_bridge: {
      sync_disk: dev.file_bridge?.sync_disk ?? false,
      engine: dev.file_bridge?.engine ?? "mutagen",
      lazy_mounts: (dev.file_bridge?.lazy_mounts ?? []).map((m) => ({ label: m.label, path: m.path })),
      lazy_mount_on_connect: dev.file_bridge?.lazy_mount_on_connect ?? false,
    },
    app_configs: {
      enabled: dev.app_configs?.enabled ?? false,
      paths: (dev.app_configs?.paths ?? []).flatMap((raw) => {
        const r = resolveEntry(raw);
        // validate.ts already rejected anything unresolvable; a survivor here is a bug.
        // `payload` is the box-side helper's file/ssh-include basename, computed once
        // here (the single source of truth — see payloadBasename) rather than left for
        // the shell to recompute from its own box path, which can name a different file.
        return "entry" in r ? [{ ...r.entry, excludes: [...r.entry.excludes], payload: payloadBasename(r.entry) }] : [];
      }),
    },
    browser: dev.browser ?? false,
    agent_config: dev.agent_config
      ? { source: dev.agent_config.source, include_settings: dev.agent_config.include_settings ?? false }
      : null,
    projects: dev.projects.map((p) => ({
      name: p.name,
      repo: p.repo,
      branch: p.branch,
      git_identity: p.git_identity,
      agent_profile: p.agent_profile,
      container_engine: p.container_engine,
      memory_space: p.memory_space,
      ports: [...p.ports],
      install: p.install,
      update: p.update,
    })),
  };
}

function normalizeDirectMemoryResources(
  resources: ResourceSpec,
  includeServiceKnobs = false,
): Record<string, unknown> {
  const normalized: Record<string, unknown> = {};
  const source = resources as unknown as Record<string, unknown>;
  const allowedKeys: readonly string[] = includeServiceKnobs ? SERVICE_RESOURCE_KEYS : SLICE_RESOURCE_KEYS;
  for (const key of allowedKeys) {
    const value = source[key];
    if (value === undefined) continue;
    normalized[key] =
      key === "memory_high" || key === "memory_max" || key === "memory_swap_max"
        ? typeof value === "string"
          ? canonicalMemorySize(value) ?? value
          : value
        : value;
  }
  return normalized;
}

const normalizeIdentity = (id: GitIdentity) => ({
  name: id.name,
  email: id.email,
  github_user: id.github_user ?? null,
});

const normalizeInstance = (i: MemoryInstance) => ({
  engine: i.engine,
  llm_provider: i.llm_provider,
  llm_model: i.llm_model ?? null,
  llm_base_url: i.llm_base_url ?? null,
  api_key_env: i.api_key_env ?? null,
});

/**
 * The layout the session comes up on: what the developer wrote, else what the client
 * running the CLI types on, else nothing (the box default, `us`).
 *
 * The detected fallback is the operator's own keyboard, so on a box with several
 * developers it is a guess for everyone but the operator — which is why `devbox plan`
 * prints where the layout came from rather than just what it is.
 */
function resolveKeyboard(dev: ResolvedDeveloper, client: ClientFacts): ResolvedKeyboard | null {
  const stated = dev.desktop?.keyboard;
  const keyboard = stated ? { layout: stated.layout, variant: stated.variant ?? null } : client.keyboard;
  if (!keyboard) return null;
  return { ...keyboard, rdp_layout_id: rdpLayoutId(keyboard) };
}

function mapValues<T, R>(
  source: Record<string, T> | undefined,
  fn: (value: T) => R,
): Record<string, R> {
  const out: Record<string, R> = {};
  for (const [key, value] of Object.entries(source ?? {})) out[key] = fn(value);
  return out;
}

/** The full generated vars file, header included. */
export function renderVars(resolved: ResolvedSpec, client: ClientFacts = NO_CLIENT_FACTS): string {
  return GENERATED_HEADER + toYaml(normalize(resolved, client));
}
