/**
 * secrets.ts — the one place a real credential is allowed to appear.
 *
 * devbox.yml never holds a secret: it holds the NAME of one (`api_key_env`,
 * `authkey_env`). The values live in devbox.secrets.yml, which is gitignored, and get
 * written to ansible/.generated/secrets.yml at 0600 for the playbook to load.
 *
 * Values are never logged or echoed. `describeSecrets` exists so `devbox plan` can show
 * which names are present without ever printing what they are.
 */
import { existsSync, chmodSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { type Issue, err, warn } from "./issues";
import type { ResolvedSpec } from "./types";
import { toYaml } from "./yaml";

export type Secrets = Record<string, string>;

export function loadSecrets(path: string): { secrets: Secrets; issues: Issue[] } {
  if (!existsSync(path)) return { secrets: {}, issues: [] };
  let raw: unknown;
  try {
    raw = Bun.YAML.parse(readFileSync(path, "utf8"));
  } catch (e) {
    return { secrets: {}, issues: [err("", `could not parse ${path}: ${(e as Error).message}`)] };
  }
  if (raw === null || raw === undefined) return { secrets: {}, issues: [] };
  if (typeof raw !== "object" || Array.isArray(raw)) {
    return { secrets: {}, issues: [err("", `${path} must be a flat NAME: value mapping`)] };
  }
  const secrets: Secrets = {};
  const issues: Issue[] = [];
  for (const [name, value] of Object.entries(raw as Record<string, unknown>)) {
    if (typeof value === "string" || typeof value === "number") {
      secrets[name] = String(value);
    } else {
      issues.push(err(name, "secret values must be scalars"));
    }
  }
  return { secrets, issues };
}

/** Check every secret required by the resolved configuration is actually present.
 * Optional integrations stay warnings so a checkout without their credentials can
 * still produce a useful plan. A desktop password is different: without it the
 * declared login path cannot work reproducibly, so that requirement fails closed. */
export function validateSecretRefs(resolved: ResolvedSpec, secrets: Secrets): Issue[] {
  const issues: Issue[] = [];
  resolved.developers.forEach((dev, i) => {
    if (dev.desktop?.enabled) {
      const name = `RDP_PASSWORD_HASH_${dev.user.toUpperCase().replaceAll("-", "_")}`;
      if (!(name in secrets)) {
        issues.push(
          err(
            `developers[${i}].desktop`,
            `'${name}' is required when desktop.enabled is true`,
          ),
        );
      }
    }
    for (const [key, instance] of Object.entries(dev.memory?.instances ?? {})) {
      const name = instance.api_key_env;
      if (name && !(name in secrets)) {
        issues.push(
          warn(
            `developers[${i}].memory.instances.${key}.api_key_env`,
            `'${name}' is not defined in devbox.secrets.yml — the memory daemon will start without a key`,
          ),
        );
      }
    }
  });
  return issues;
}

/** Names only — never values. Safe to print. */
export const describeSecrets = (secrets: Secrets): string[] => Object.keys(secrets).sort();

const GENERATED_HEADER = [
  "---",
  "# GENERATED by `devbox plan --write-vars` — DO NOT EDIT, DO NOT COMMIT.",
  "# Source of truth: devbox.secrets.yml.",
  "",
].join("\n");

/** Write the secrets Ansible loads. Mode 0600: this file holds real credentials. */
export function writeGeneratedSecrets(secrets: Secrets, repoRoot: string): string {
  const dir = join(repoRoot, "ansible", ".generated");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "secrets.yml");
  writeFileSync(path, GENERATED_HEADER + toYaml({ devbox_secrets: secrets }), { mode: 0o600 });
  chmodSync(path, 0o600); // writeFileSync's mode is ignored when the file already exists
  return path;
}
