"""Unit tests for the resume scanner's name resolution.

Run: python3 -m unittest discover -s scripts -p 'test_*.py' -t scripts
"""
import importlib.util
import pathlib
import unittest


def _load(name, filename):
    path = pathlib.Path(__file__).with_name(filename)
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


scan = _load("agent_rc_resume_scan", "agent-rc-resume-scan.py")

UUID = "393f13d9-46d0-4dba-8f77-e9bc02a630a3"


def user(text, **kw):
    rec = {"type": "user", "message": {"role": "user", "content": text}}
    rec.update(kw)
    return rec


class ResolveName(unittest.TestCase):
    def test_a_killed_workflow_names_the_session(self):
        killed = [{"name": "review-changes", "runId": "wf_1"}]
        self.assertEqual(
            scan.resolve_name([user("bir seyler yap")], killed, "Verti Monorepo", UUID),
            "review-changes")

    def test_custom_title_beats_the_first_message(self):
        recs = [user("ilk mesaj"),
                {"type": "custom-title", "customTitle": "Gmail OAuth credentials setup"}]
        self.assertEqual(scan.resolve_name(recs, [], "Verti Monorepo", UUID),
                         "Gmail OAuth credentials setup")

    def test_falls_back_to_the_first_human_line(self):
        recs = [
            user("Caveat: The messages below were generated by the user", isMeta=True),
            user("<command-name>/resume</command-name>"),
            user("dashboard ozet yukleme hatasina bakar misin\nikinci satir"),
        ]
        self.assertEqual(scan.resolve_name(recs, [], "Verti Monorepo", UUID),
                         "dashboard ozet yukleme hatasina bakar misin")

    def test_reads_block_style_content(self):
        recs = [{"type": "user", "message": {"content": [{"type": "text", "text": "blok mesaj"}]}}]
        self.assertEqual(scan.resolve_name(recs, [], "Verti Monorepo", UUID), "blok mesaj")

    def test_ignores_our_own_resume_notice(self):
        recs = [user("[automated resume notice - system, not the user] The host OOM-killed this run")]
        self.assertEqual(scan.resolve_name(recs, [], "Verti Monorepo", UUID),
                         "Verti Monorepo · 393f13d9")

    def test_truncates_a_long_line(self):
        self.assertEqual(len(scan.resolve_name([user("x" * 200)], [], "P", UUID)), 60)

    def test_last_resort_is_the_project_and_uuid_prefix(self):
        self.assertEqual(scan.resolve_name([], [], "Verti Monorepo", UUID),
                         "Verti Monorepo · 393f13d9")

    def test_an_empty_workflow_name_does_not_win(self):
        killed = [{"name": "", "runId": "wf_1"}]
        self.assertEqual(scan.resolve_name([user("gercek mesaj")], killed, "P", UUID),
                         "gercek mesaj")

    def test_system_reminder_block_first_human_text_second(self):
        """Regression test for Finding 1: system-reminder in same record should not mask human text."""
        recs = [{
            "type": "user",
            "message": {
                "content": [
                    {"type": "text", "text": "<system-reminder>…</system-reminder>"},
                    {"type": "text", "text": "genuine user message here"},
                ]
            }
        }]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "genuine user message here")

    def test_system_reminder_only_then_real_text(self):
        """Regression test: system-reminder-only record followed by real text in next record."""
        recs = [
            {
                "type": "user",
                "message": {
                    "content": [
                        {"type": "text", "text": "<system-reminder>automated noise</system-reminder>"},
                    ]
                }
            },
            user("real user message"),
        ]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "real user message")

    def test_text_blocks_handles_record_without_message_key(self):
        """Degradation test: record missing message key should be skipped gracefully."""
        recs = [{"type": "user"}]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "Project · 393f13d9")

    def test_text_blocks_handles_message_not_dict(self):
        """Degradation test: message that is not a dict should be skipped gracefully."""
        recs = [{"type": "user", "message": "not a dict"}]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "Project · 393f13d9")

    def test_text_blocks_handles_content_is_none(self):
        """Degradation test: content that is None should yield no blocks."""
        recs = [{"type": "user", "message": {"content": None}}]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "Project · 393f13d9")

    def test_text_blocks_handles_content_is_dict(self):
        """Degradation test: content that is a dict (not string or list) should be skipped."""
        recs = [{"type": "user", "message": {"content": {"type": "text", "text": "data"}}}]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "Project · 393f13d9")

    def test_text_blocks_handles_list_without_text_key(self):
        """Degradation test: content list with blocks lacking 'text' key should yield empty blocks."""
        recs = [{
            "type": "user",
            "message": {
                "content": [
                    {"type": "text"},  # missing "text" key
                    {"type": "code", "code": "print('hello')"},  # wrong type
                ]
            }
        }]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "Project · 393f13d9")

    def test_null_text_block_does_not_abort_and_real_text_still_found(self):
        """Regression test for Finding 1: a `"text": null` block must not raise
        AttributeError in first_user_line (block.strip() on None) -- it should be
        skipped like an empty string, letting a later real block win."""
        recs = [{
            "type": "user",
            "message": {
                "content": [
                    {"type": "text", "text": None},
                    {"type": "text", "text": "real message after the null block"},
                ]
            }
        }]
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID),
                         "real message after the null block")

    def test_numeric_text_block_is_coerced_not_fatal(self):
        """Regression test for Finding 1: a non-string 'text' value (e.g. a number)
        must be neutralised rather than raising when .strip() is called on it."""
        recs = [{
            "type": "user",
            "message": {
                "content": [
                    {"type": "text", "text": 42},
                ]
            }
        }]
        # A bare "42" is a valid (if odd) first line -- the point is that resolving
        # the name does not raise.
        self.assertEqual(scan.resolve_name(recs, [], "Project", UUID), "42")


if __name__ == "__main__":
    unittest.main()
